bool containsBulletPoints(std::string commit_msg, int count);
bool containsCorrectNitFormat(std::string commit_msg);
bool containsCorrectWIPFormat(std::string commit_msg);
bool containsDescription(std::string commit_msg);
bool containsTypos(std::string commit_msg);
bool isDescriptionMaxLength(std::string commit_msg, int length);
bool isDescriptionMinLength(std::string commit_msg, int length);
bool isFirstLetterCapitalized(std::string commit_msg);
bool isSummaryMaxLength(std::string commit_msg, int length);
bool isSummaryMinLength(std::string commit_msg, int length);
